<?php

namespace Database\Seeders;

use App\Core\Email\EmailTemplate;
use Illuminate\Database\Seeder;

class EmailTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'key' => 'billing.trial_started',
                'category' => 'billing',
                'name' => 'Trial Started',
                'subject_fr' => 'Bienvenue sur {{ plan_name }} — Votre essai démarre',
                'subject_en' => 'Welcome to {{ plan_name }} — Your trial begins',
                'body_fr' => "Bonjour {{ user_name }},\n\nBienvenue chez Leezr ! Votre essai gratuit de {{ trial_days }} jours sur le plan {{ plan_name }} est maintenant actif pour {{ company_name }}.\n\nProfitez de toutes les fonctionnalités durant cette période pour découvrir comment Leezr peut simplifier votre gestion.\n\nBonne découverte,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nWelcome to Leezr! Your {{ trial_days }}-day free trial on the {{ plan_name }} plan is now active for {{ company_name }}.\n\nEnjoy full access to all features during this period and discover how Leezr can streamline your operations.\n\nHappy exploring,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'trial_days', 'plan_name'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'trial_days' => '14',
                    'plan_name' => 'Pro',
                ],
            ],
            [
                'key' => 'billing.trial_expiring',
                'category' => 'billing',
                'name' => 'Trial Expiring',
                'subject_fr' => 'Votre essai {{ plan_name }} expire dans {{ days_remaining }} jours',
                'subject_en' => 'Your {{ plan_name }} trial expires in {{ days_remaining }} days',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre essai gratuit du plan {{ plan_name }} pour {{ company_name }} se termine le {{ trial_ends_at }}. Il vous reste {{ days_remaining }} jours pour profiter de toutes les fonctionnalités.\n\nPour continuer sans interruption, ajoutez un moyen de paiement dès maintenant.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour free trial of the {{ plan_name }} plan for {{ company_name }} ends on {{ trial_ends_at }}. You have {{ days_remaining }} days remaining to enjoy all features.\n\nTo continue without interruption, add a payment method now.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'trial_ends_at', 'days_remaining', 'plan_name'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'trial_ends_at' => '2026-05-01',
                    'days_remaining' => '3',
                    'plan_name' => 'Pro',
                ],
            ],
            [
                'key' => 'billing.trial_converted',
                'category' => 'billing',
                'name' => 'Trial Converted',
                'subject_fr' => 'Votre abonnement {{ plan_name }} est maintenant actif',
                'subject_en' => 'Your {{ plan_name }} subscription is now active',
                'body_fr' => "Bonjour {{ user_name }},\n\nFélicitations ! Votre essai a été converti avec succès. L'abonnement {{ plan_name }} est désormais actif pour {{ company_name }}.\n\nVous bénéficiez maintenant d'un accès complet et continu à toutes les fonctionnalités de votre plan.\n\nMerci pour votre confiance,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nCongratulations! Your trial has been successfully converted. The {{ plan_name }} subscription is now active for {{ company_name }}.\n\nYou now have full, uninterrupted access to all features included in your plan.\n\nThank you for your trust,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'plan_name'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'plan_name' => 'Pro',
                ],
            ],
            [
                'key' => 'billing.invoice_created',
                'category' => 'billing',
                'name' => 'Invoice Created',
                'subject_fr' => 'Nouvelle facture {{ invoice_number }} — {{ amount }} {{ currency }}',
                'subject_en' => 'New invoice {{ invoice_number }} — {{ amount }} {{ currency }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nUne nouvelle facture a été émise pour {{ company_name }}.\n\nFacture : {{ invoice_number }}\nMontant : {{ amount }} {{ currency }}\n\nVous pouvez la consulter et la régler depuis votre espace de facturation.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nA new invoice has been issued for {{ company_name }}.\n\nInvoice: {{ invoice_number }}\nAmount: {{ amount }} {{ currency }}\n\nYou can view and pay it from your billing dashboard.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'invoice_number', 'amount', 'currency'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'invoice_number' => 'INV-2026-0042',
                    'amount' => '99.00',
                    'currency' => 'EUR',
                ],
            ],
            [
                'key' => 'billing.payment_received',
                'category' => 'billing',
                'name' => 'Payment Received',
                'subject_fr' => 'Paiement reçu — Facture {{ invoice_number }}',
                'subject_en' => 'Payment received — Invoice {{ invoice_number }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nNous confirmons la réception de votre paiement de {{ amount }} {{ currency }} pour la facture {{ invoice_number }} de {{ company_name }}.\n\nVotre reçu est disponible dans votre espace de facturation.\n\nMerci,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nWe confirm receipt of your payment of {{ amount }} {{ currency }} for invoice {{ invoice_number }} from {{ company_name }}.\n\nYour receipt is available in your billing dashboard.\n\nThank you,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'invoice_number', 'amount', 'currency'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'invoice_number' => 'INV-2026-0042',
                    'amount' => '99.00',
                    'currency' => 'EUR',
                ],
            ],
            [
                'key' => 'billing.payment_failed',
                'category' => 'billing',
                'name' => 'Payment Failed',
                'subject_fr' => 'Échec de paiement — Facture {{ invoice_number }}',
                'subject_en' => 'Payment failed — Invoice {{ invoice_number }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nLe paiement de {{ amount }} {{ currency }} pour la facture {{ invoice_number }} de {{ company_name }} a échoué.\n\nVeuillez vérifier votre moyen de paiement et réessayer depuis votre espace de facturation pour éviter toute interruption de service.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nThe payment of {{ amount }} {{ currency }} for invoice {{ invoice_number }} from {{ company_name }} has failed.\n\nPlease verify your payment method and retry from your billing dashboard to avoid any service interruption.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'invoice_number', 'amount', 'currency'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'invoice_number' => 'INV-2026-0042',
                    'amount' => '99.00',
                    'currency' => 'EUR',
                ],
            ],
            [
                'key' => 'billing.payment_method_expiring',
                'category' => 'billing',
                'name' => 'Payment Method Expiring',
                'subject_fr' => 'Votre carte {{ card_brand }} se termine bientôt',
                'subject_en' => 'Your {{ card_brand }} card is expiring soon',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre carte {{ card_brand }} terminant par {{ card_last4 }} expire le {{ expiry_date }}.\n\nPour éviter toute interruption de vos paiements, veuillez mettre à jour votre moyen de paiement dans votre espace de facturation.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour {{ card_brand }} card ending in {{ card_last4 }} expires on {{ expiry_date }}.\n\nTo avoid any payment disruption, please update your payment method in your billing dashboard.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'card_brand', 'card_last4', 'expiry_date'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'card_brand' => 'Visa',
                    'card_last4' => '4242',
                    'expiry_date' => '06/2026',
                ],
            ],
            [
                'key' => 'billing.plan_changed',
                'category' => 'billing',
                'name' => 'Plan Changed',
                'subject_fr' => 'Changement de plan : {{ old_plan }} → {{ new_plan }}',
                'subject_en' => 'Plan changed: {{ old_plan }} → {{ new_plan }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nLe plan de {{ company_name }} a été modifié avec succès.\n\nAncien plan : {{ old_plan }}\nNouveau plan : {{ new_plan }}\n\nLes nouvelles fonctionnalités sont disponibles immédiatement.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nThe plan for {{ company_name }} has been successfully updated.\n\nPrevious plan: {{ old_plan }}\nNew plan: {{ new_plan }}\n\nThe new features are available immediately.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'old_plan', 'new_plan'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'old_plan' => 'Starter',
                    'new_plan' => 'Pro',
                ],
            ],
            [
                'key' => 'billing.addon_activated',
                'category' => 'billing',
                'name' => 'Addon Activated',
                'subject_fr' => 'Module {{ module_name }} activé pour {{ company_name }}',
                'subject_en' => '{{ module_name }} module activated for {{ company_name }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nLe module {{ module_name }} a été activé avec succès pour {{ company_name }}.\n\nMontant : {{ amount }} {{ currency }} / mois\n\nVous pouvez commencer à l'utiliser dès maintenant depuis votre tableau de bord.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nThe {{ module_name }} module has been successfully activated for {{ company_name }}.\n\nAmount: {{ amount }} {{ currency }} / month\n\nYou can start using it right away from your dashboard.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'module_name', 'amount', 'currency'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'module_name' => 'Documents AI',
                    'amount' => '29.00',
                    'currency' => 'EUR',
                ],
            ],
            [
                'key' => 'billing.account_suspended',
                'category' => 'billing',
                'name' => 'Account Suspended',
                'subject_fr' => 'Compte {{ company_name }} suspendu — Action requise',
                'subject_en' => '{{ company_name }} account suspended — Action required',
                'body_fr' => "Bonjour {{ user_name }},\n\nLe compte de {{ company_name }} a été suspendu en raison d'impayés. L'accès aux fonctionnalités est temporairement restreint.\n\nPour réactiver votre compte, veuillez régulariser votre situation depuis votre espace de facturation.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nThe account for {{ company_name }} has been suspended due to unpaid invoices. Access to features is temporarily restricted.\n\nTo reactivate your account, please settle your outstanding balance from your billing dashboard.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name'],
                'is_system' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                ],
            ],
            [
                'key' => 'billing.critical_alert',
                'category' => 'billing',
                'name' => 'Critical Alert',
                'subject_fr' => '[ALERTE] {{ severity }} — {{ action }} sur {{ target_type }} #{{ target_id }}',
                'subject_en' => '[ALERT] {{ severity }} — {{ action }} on {{ target_type }} #{{ target_id }}',
                'body_fr' => "Alerte plateforme détectée.\n\nAction : {{ action }}\nType : {{ target_type }}\nIdentifiant : {{ target_id }}\nSévérité : {{ severity }}\nDate : {{ timestamp }}\n\nVeuillez vérifier cette activité dans le panneau d'administration.\n\n— Système Leezr",
                'body_en' => "Platform alert detected.\n\nAction: {{ action }}\nType: {{ target_type }}\nIdentifier: {{ target_id }}\nSeverity: {{ severity }}\nDate: {{ timestamp }}\n\nPlease review this activity in the admin panel.\n\n— Leezr System",
                'variables' => ['action', 'target_type', 'target_id', 'severity', 'timestamp'],
                'is_system' => true,
                'preview_data' => [
                    'action' => 'force_cancel',
                    'target_type' => 'subscription',
                    'target_id' => '1042',
                    'severity' => 'critical',
                    'timestamp' => '2026-04-16 14:30:00',
                ],
            ],

            // ─── Onboarding ───────────────────────────────────────────────

            [
                'key' => 'onboarding.welcome',
                'category' => 'onboarding',
                'name' => 'Welcome',
                'subject_fr' => 'Bienvenue sur {{ app_name }}, {{ user_name }} !',
                'subject_en' => 'Welcome to {{ app_name }}, {{ user_name }}!',
                'body_fr' => "Bonjour {{ user_name }},\n\nBienvenue sur {{ app_name }} ! Votre compte a été créé avec succès pour {{ company_name }}.\n\nVous pouvez dès maintenant accéder à votre espace et commencer à configurer votre environnement.\n\nSi vous avez la moindre question, notre équipe support est à votre disposition.\n\nÀ très bientôt,\nL'équipe {{ app_name }}",
                'body_en' => "Hello {{ user_name }},\n\nWelcome to {{ app_name }}! Your account has been successfully created for {{ company_name }}.\n\nYou can now access your workspace and start setting up your environment.\n\nIf you have any questions, our support team is here to help.\n\nSee you soon,\nThe {{ app_name }} Team",
                'variables' => ['user_name', 'company_name', 'app_name'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'company_name' => 'ACME Corp',
                    'app_name' => 'Leezr',
                ],
            ],
            [
                'key' => 'onboarding.invite_member',
                'category' => 'onboarding',
                'name' => 'Member Invitation',
                'subject_fr' => '{{ inviter_name }} vous invite à rejoindre {{ company_name }}',
                'subject_en' => '{{ inviter_name }} invites you to join {{ company_name }}',
                'body_fr' => "Bonjour {{ user_name }},\n\n{{ inviter_name }} vous invite à rejoindre l'espace {{ company_name }} sur Leezr.\n\nCliquez sur le lien ci-dessous pour accepter l'invitation et créer votre accès :\n\n{{ invite_url }}\n\nCe lien est valable pour une durée limitée.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\n{{ inviter_name }} invites you to join the {{ company_name }} workspace on Leezr.\n\nClick the link below to accept the invitation and set up your access:\n\n{{ invite_url }}\n\nThis link is valid for a limited time.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'inviter_name', 'invite_url'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                    'inviter_name' => 'Jean Dupont',
                    'invite_url' => 'https://leezr.com/invite/abc123',
                ],
            ],

            // ─── Support ──────────────────────────────────────────────────

            [
                'key' => 'support.ticket_created',
                'category' => 'support',
                'name' => 'Ticket Created',
                'subject_fr' => 'Ticket #{{ ticket_id }} créé — {{ ticket_subject }}',
                'subject_en' => 'Ticket #{{ ticket_id }} created — {{ ticket_subject }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre ticket de support a bien été créé.\n\nTicket : #{{ ticket_id }}\nSujet : {{ ticket_subject }}\n\nNotre équipe va examiner votre demande et vous répondre dans les meilleurs délais. Vous recevrez une notification à chaque mise à jour.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour support ticket has been successfully created.\n\nTicket: #{{ ticket_id }}\nSubject: {{ ticket_subject }}\n\nOur team will review your request and respond as soon as possible. You will receive a notification for each update.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'ticket_id', 'ticket_subject'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'ticket_id' => '1042',
                    'ticket_subject' => 'Problème de connexion au tableau de bord',
                ],
            ],
            [
                'key' => 'support.ticket_reply',
                'category' => 'support',
                'name' => 'Ticket Reply',
                'subject_fr' => 'Nouvelle réponse sur le ticket #{{ ticket_id }}',
                'subject_en' => 'New reply on ticket #{{ ticket_id }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nUne nouvelle réponse a été ajoutée à votre ticket de support.\n\nTicket : #{{ ticket_id }}\nSujet : {{ ticket_subject }}\n\nExtrait de la réponse :\n{{ reply_excerpt }}\n\nConsultez votre espace support pour voir la réponse complète et poursuivre la conversation.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nA new reply has been added to your support ticket.\n\nTicket: #{{ ticket_id }}\nSubject: {{ ticket_subject }}\n\nReply excerpt:\n{{ reply_excerpt }}\n\nVisit your support dashboard to see the full reply and continue the conversation.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'ticket_id', 'ticket_subject', 'reply_excerpt'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'ticket_id' => '1042',
                    'ticket_subject' => 'Problème de connexion au tableau de bord',
                    'reply_excerpt' => 'Nous avons identifié le problème et une correction est en cours de déploiement...',
                ],
            ],
            [
                'key' => 'support.ticket_closed',
                'category' => 'support',
                'name' => 'Ticket Closed',
                'subject_fr' => 'Ticket #{{ ticket_id }} résolu',
                'subject_en' => 'Ticket #{{ ticket_id }} resolved',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre ticket de support a été marqué comme résolu.\n\nTicket : #{{ ticket_id }}\nSujet : {{ ticket_subject }}\n\nSi le problème persiste ou si vous avez d'autres questions, n'hésitez pas à rouvrir ce ticket ou à en créer un nouveau.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour support ticket has been marked as resolved.\n\nTicket: #{{ ticket_id }}\nSubject: {{ ticket_subject }}\n\nIf the issue persists or you have further questions, feel free to reopen this ticket or create a new one.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'ticket_id', 'ticket_subject'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'ticket_id' => '1042',
                    'ticket_subject' => 'Problème de connexion au tableau de bord',
                ],
            ],

            // ─── Documents ────────────────────────────────────────────────

            [
                'key' => 'documents.request_created',
                'category' => 'documents',
                'name' => 'Document Request',
                'subject_fr' => 'Demande de document — {{ document_type }}',
                'subject_en' => 'Document request — {{ document_type }}',
                'body_fr' => "Bonjour {{ user_name }},\n\n{{ company_name }} vous demande de fournir le document suivant :\n\nType de document : {{ document_type }}\nDate limite : {{ due_date }}\n\nMerci de déposer ce document dans votre espace personnel avant la date indiquée.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\n{{ company_name }} requests that you provide the following document:\n\nDocument type: {{ document_type }}\nDue date: {{ due_date }}\n\nPlease upload this document to your personal space before the deadline.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'document_type', 'due_date'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                    'document_type' => 'Carte d\'identité',
                    'due_date' => '2026-05-15',
                ],
            ],
            [
                'key' => 'documents.expiring_soon',
                'category' => 'documents',
                'name' => 'Document Expiring',
                'subject_fr' => 'Document {{ document_type }} expire dans {{ days_remaining }} jours',
                'subject_en' => 'Document {{ document_type }} expires in {{ days_remaining }} days',
                'body_fr' => "Bonjour {{ user_name }},\n\nLe document suivant arrive bientôt à expiration :\n\nEntreprise : {{ company_name }}\nType de document : {{ document_type }}\nDate d'expiration : {{ expiry_date }}\nJours restants : {{ days_remaining }}\n\nMerci de fournir une version à jour avant l'échéance pour rester en conformité.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nThe following document is expiring soon:\n\nCompany: {{ company_name }}\nDocument type: {{ document_type }}\nExpiry date: {{ expiry_date }}\nDays remaining: {{ days_remaining }}\n\nPlease provide an updated version before the deadline to stay compliant.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'document_type', 'expiry_date', 'days_remaining'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                    'document_type' => 'Attestation d\'assurance',
                    'expiry_date' => '2026-05-01',
                    'days_remaining' => '15',
                ],
            ],
            [
                'key' => 'documents.approved',
                'category' => 'documents',
                'name' => 'Document Approved',
                'subject_fr' => 'Document {{ document_type }} validé',
                'subject_en' => 'Document {{ document_type }} approved',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre document a été examiné et validé avec succès.\n\nEntreprise : {{ company_name }}\nType de document : {{ document_type }}\n\nAucune action supplémentaire n'est requise de votre part.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour document has been reviewed and approved successfully.\n\nCompany: {{ company_name }}\nDocument type: {{ document_type }}\n\nNo further action is required on your part.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'document_type'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                    'document_type' => 'Carte d\'identité',
                ],
            ],

            // ─── Maintenance ──────────────────────────────────────────────

            [
                'key' => 'maintenance.scheduled',
                'category' => 'maintenance',
                'name' => 'Scheduled Maintenance',
                'subject_fr' => 'Maintenance planifiée — {{ app_name }}',
                'subject_en' => 'Scheduled maintenance — {{ app_name }}',
                'body_fr' => "Bonjour,\n\nUne maintenance planifiée de {{ app_name }} est prévue.\n\nDate : {{ maintenance_date }}\nDurée estimée : {{ maintenance_duration }}\nDescription : {{ maintenance_description }}\n\nLe service pourra être temporairement indisponible pendant cette période. Nous nous excusons pour la gêne occasionnée.\n\nCordialement,\nL'équipe {{ app_name }}",
                'body_en' => "Hello,\n\nA scheduled maintenance for {{ app_name }} is planned.\n\nDate: {{ maintenance_date }}\nEstimated duration: {{ maintenance_duration }}\nDescription: {{ maintenance_description }}\n\nThe service may be temporarily unavailable during this period. We apologize for any inconvenience.\n\nBest regards,\nThe {{ app_name }} Team",
                'variables' => ['app_name', 'maintenance_date', 'maintenance_duration', 'maintenance_description'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'app_name' => 'Leezr',
                    'maintenance_date' => '2026-05-01 02:00 UTC',
                    'maintenance_duration' => '2 heures',
                    'maintenance_description' => 'Mise à jour de la base de données et optimisation des performances',
                ],
            ],
            [
                'key' => 'maintenance.completed',
                'category' => 'maintenance',
                'name' => 'Maintenance Completed',
                'subject_fr' => 'Maintenance terminée — {{ app_name }} est de retour',
                'subject_en' => 'Maintenance completed — {{ app_name }} is back',
                'body_fr' => "Bonjour,\n\nLa maintenance planifiée de {{ app_name }} le {{ maintenance_date }} est maintenant terminée.\n\nTous les services sont de nouveau opérationnels. Si vous rencontrez un problème, n'hésitez pas à contacter notre support.\n\nCordialement,\nL'équipe {{ app_name }}",
                'body_en' => "Hello,\n\nThe scheduled maintenance for {{ app_name }} on {{ maintenance_date }} is now complete.\n\nAll services are fully operational again. If you experience any issues, please contact our support team.\n\nBest regards,\nThe {{ app_name }} Team",
                'variables' => ['app_name', 'maintenance_date'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'app_name' => 'Leezr',
                    'maintenance_date' => '2026-05-01 02:00 UTC',
                ],
            ],
            [
                'key' => 'maintenance.incident',
                'category' => 'maintenance',
                'name' => 'Service Incident',
                'subject_fr' => '[Incident] {{ app_name }} — {{ status }}',
                'subject_en' => '[Incident] {{ app_name }} — {{ status }}',
                'body_fr' => "Bonjour,\n\nNous avons détecté un incident affectant {{ app_name }}.\n\nDescription : {{ incident_description }}\nStatut : {{ status }}\n\nNos équipes travaillent activement à la résolution de ce problème. Vous serez informé dès que le service sera rétabli.\n\nCordialement,\nL'équipe {{ app_name }}",
                'body_en' => "Hello,\n\nWe have detected an incident affecting {{ app_name }}.\n\nDescription: {{ incident_description }}\nStatus: {{ status }}\n\nOur teams are actively working to resolve this issue. You will be notified once the service is restored.\n\nBest regards,\nThe {{ app_name }} Team",
                'variables' => ['app_name', 'incident_description', 'status'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'app_name' => 'Leezr',
                    'incident_description' => 'Latence élevée sur le service de facturation',
                    'status' => 'En cours d\'investigation',
                ],
            ],

            // ─── Members ──────────────────────────────────────────────────

            [
                'key' => 'members.role_changed',
                'category' => 'members',
                'name' => 'Role Changed',
                'subject_fr' => 'Votre rôle a été modifié chez {{ company_name }}',
                'subject_en' => 'Your role has been changed at {{ company_name }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre rôle au sein de {{ company_name }} a été modifié.\n\nAncien rôle : {{ old_role }}\nNouveau rôle : {{ new_role }}\n\nVos permissions ont été mises à jour en conséquence. Si vous avez des questions, contactez votre administrateur.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour role within {{ company_name }} has been changed.\n\nPrevious role: {{ old_role }}\nNew role: {{ new_role }}\n\nYour permissions have been updated accordingly. If you have any questions, please contact your administrator.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name', 'old_role', 'new_role'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                    'old_role' => 'Membre',
                    'new_role' => 'Administrateur',
                ],
            ],
            [
                'key' => 'members.removed',
                'category' => 'members',
                'name' => 'Removed from Company',
                'subject_fr' => 'Vous avez été retiré de {{ company_name }}',
                'subject_en' => 'You have been removed from {{ company_name }}',
                'body_fr' => "Bonjour {{ user_name }},\n\nVous avez été retiré de l'espace {{ company_name }} sur Leezr.\n\nVous n'avez plus accès aux données et fonctionnalités de cette entreprise. Si vous pensez qu'il s'agit d'une erreur, veuillez contacter l'administrateur de {{ company_name }}.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYou have been removed from the {{ company_name }} workspace on Leezr.\n\nYou no longer have access to this company's data and features. If you believe this is an error, please contact the administrator of {{ company_name }}.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'company_name'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Marie Martin',
                    'company_name' => 'ACME Corp',
                ],
            ],

            // ─── Security ─────────────────────────────────────────────────

            [
                'key' => 'security.password_changed',
                'category' => 'security',
                'name' => 'Password Changed',
                'subject_fr' => 'Votre mot de passe a été modifié',
                'subject_en' => 'Your password has been changed',
                'body_fr' => "Bonjour {{ user_name }},\n\nVotre mot de passe Leezr a été modifié avec succès le {{ changed_at }}.\n\nSi vous n'êtes pas à l'origine de cette modification, veuillez immédiatement réinitialiser votre mot de passe et contacter notre support.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nYour Leezr password was successfully changed on {{ changed_at }}.\n\nIf you did not make this change, please immediately reset your password and contact our support team.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'changed_at'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'changed_at' => '2026-04-16 14:30:00',
                ],
            ],
            [
                'key' => 'security.login_new_device',
                'category' => 'security',
                'name' => 'New Device Login',
                'subject_fr' => 'Connexion depuis un nouvel appareil',
                'subject_en' => 'Login from a new device',
                'body_fr' => "Bonjour {{ user_name }},\n\nUne connexion à votre compte Leezr a été détectée depuis un nouvel appareil.\n\nAppareil : {{ device_info }}\nDate : {{ login_at }}\nAdresse IP : {{ ip_address }}\n\nSi vous êtes à l'origine de cette connexion, aucune action n'est nécessaire. Dans le cas contraire, modifiez immédiatement votre mot de passe et contactez notre support.\n\nCordialement,\nL'équipe Leezr",
                'body_en' => "Hello {{ user_name }},\n\nA login to your Leezr account was detected from a new device.\n\nDevice: {{ device_info }}\nDate: {{ login_at }}\nIP address: {{ ip_address }}\n\nIf this was you, no action is needed. Otherwise, please change your password immediately and contact our support team.\n\nBest regards,\nThe Leezr Team",
                'variables' => ['user_name', 'device_info', 'login_at', 'ip_address'],
                'is_system' => true,
                'is_active' => true,
                'preview_data' => [
                    'user_name' => 'Jean Dupont',
                    'device_info' => 'Chrome 120 sur macOS',
                    'login_at' => '2026-04-16 14:30:00',
                    'ip_address' => '192.168.1.42',
                ],
            ],
        ];

        foreach ($templates as $template) {
            EmailTemplate::updateOrCreate(
                ['key' => $template['key']],
                $template,
            );
        }
    }
}
