/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-settings-tab': RouteRecordInfo<'account-settings-tab', '/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'company-jobdomain': RouteRecordInfo<'company-jobdomain', '/company/jobdomain', Record<never, never>, Record<never, never>>,
    'company-members': RouteRecordInfo<'company-members', '/company/members', Record<never, never>, Record<never, never>>,
    'company-modules': RouteRecordInfo<'company-modules', '/company/modules', Record<never, never>, Record<never, never>>,
    'company-settings': RouteRecordInfo<'company-settings', '/company/settings', Record<never, never>, Record<never, never>>,
    'company-shipments': RouteRecordInfo<'company-shipments', '/company/shipments', Record<never, never>, Record<never, never>>,
    'company-shipments-id': RouteRecordInfo<'company-shipments-id', '/company/shipments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'company-shipments-create': RouteRecordInfo<'company-shipments-create', '/company/shipments/create', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'platform': RouteRecordInfo<'platform', '/platform', Record<never, never>, Record<never, never>>,
    'platform-companies': RouteRecordInfo<'platform-companies', '/platform/companies', Record<never, never>, Record<never, never>>,
    'platform-company-users': RouteRecordInfo<'platform-company-users', '/platform/company/users', Record<never, never>, Record<never, never>>,
    'platform-login': RouteRecordInfo<'platform-login', '/platform/login', Record<never, never>, Record<never, never>>,
    'platform-modules': RouteRecordInfo<'platform-modules', '/platform/modules', Record<never, never>, Record<never, never>>,
    'platform-roles': RouteRecordInfo<'platform-roles', '/platform/roles', Record<never, never>, Record<never, never>>,
    'platform-users': RouteRecordInfo<'platform-users', '/platform/users', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
  }
}
