<?php

namespace App\Modules\Workforce\UseCases;

use App\Core\Audit\AuditLogger;
use App\Core\Workforce\PayrollRun;
use Illuminate\Support\Facades\DB;

class RecomputePayrollUseCase
{
    public function execute(PayrollRun $run, int $actorId): PayrollRun
    {
        // Guard: only from computed status
        if ($run->status !== PayrollRun::STATUS_COMPUTED) {
            throw new \DomainException("Cannot recompute PayrollRun: status is '{$run->status}', expected 'computed'.");
        }

        // Audit old snapshot summary before deletion
        $oldSummary = [
            'employee_count' => $run->employee_count,
            'total_gross_cents' => $run->total_gross_cents,
            'total_worked_minutes' => $run->total_worked_minutes,
            'total_overtime_minutes' => $run->total_overtime_minutes,
            'anomaly_count' => $run->anomaly_count,
            'computed_at' => $run->computed_at?->toIso8601String(),
        ];

        DB::transaction(function () use ($run) {
            $run = PayrollRun::withoutGlobalScopes()->lockForUpdate()->findOrFail($run->id);

            // Transition back to draft (clear computed state)
            $run->transitionTo(PayrollRun::STATUS_DRAFT);
            $run->computed_by = null;
            $run->computed_at = null;
            $run->total_gross_cents = 0;
            $run->total_worked_minutes = 0;
            $run->total_overtime_minutes = 0;
            $run->total_leave_days_hundredths = 0;
            $run->employee_count = 0;
            $run->anomalies = null;
            $run->anomaly_count = 0;
            $run->policy_snapshot = null;
            $run->pay_frequency_scope = null;
            $run->save();

            // Lines will be deleted + regenerated by ComputePayrollUseCase
            $run->lines()->delete();
        });

        $run->refresh();

        app(AuditLogger::class)->logCompany(
            companyId: $run->company_id,
            action: 'payroll_run.recompute_initiated',
            targetType: 'payroll_run',
            targetId: (string) $run->id,
            options: [
                'actorId' => $actorId,
                'metadata' => [
                    'category' => 'workforce.payroll',
                    'old_summary' => $oldSummary,
                    'description' => 'PayrollRun reverted to draft for recompute',
                ],
            ],
        );

        // Now compute fresh
        return app(ComputePayrollUseCase::class)->execute($run, $actorId);
    }
}
